name: Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "gradle.properties"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
