name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle.properties'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          keystore-name: 'keystore.jks'
          retention-days: 3
