name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle.properties'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          store-base64: ${{ secrets.STORE_BASE64 }}
          store-password: ${{ secrets.STORE_PASSWORD }}
          store-location: ${{ secrets.STORE_LOCATION }}
          store-name: 'keystore.jks'
          retention-days: 3
