name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle.properties'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Decode keystore
        run: |
          pwd
          ls -ahl
          echo ${{ secrets.SIGNING_KEY_STORE_BASE64 }} > ./keystore_b64.txt
          cd ./app
          pwd
          ls -ahl
          base64 -di ./keystore_b64.txt > ./app/keystore.jks

      - name: Update the permission
        run: chmod +x ./gradlew

#       - name: Build APK
#         env:
#           SIGNING_KEY_STORE_PATH: ~/keystore.jks
#           SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#           SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#           SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#         run: ./gradlew assembleRelease --stacktrace
#
#       - name: Build bundle
#         env:
#           SIGNING_KEY_STORE_PATH: ~/keystore.jks
#           SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#           SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#           SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#         run: ./gradlew bundleRelease --stacktrace

      - name: Build APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          pwd
          ls -ahl
          ./gradlew app:assemble

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.sha }}
          path: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/
          retention-days: 3
