name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          store-base64: ${{ secrets.STORE_BASE64 }}
          store-password: ${{ secrets.STORE_PASSWORD }}
          store-location: ${{ secrets.STORE_LOCATION }}
          store-name: 'keystore.jks'
          retention-days: 3

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-${{ github.sha }}

      - name: Show
        run: |
          pwd
          ls -alh
