name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          store-base64: ${{ secrets.STORE_BASE64 }}
          store-password: ${{ secrets.STORE_PASSWORD }}
          store-location: ${{ secrets.STORE_LOCATION }}
          store-name: 'keystore.jks'
          retention-days: 3 # can remove this to use default number of days from repo settings

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      # for release action
      contents: write
      # for attestation creation action
      id-token: write
      attestations: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-${{ github.sha }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.apk

      - name: Attest artifact
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: ./*.apk
