name: Release

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle.properties'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build
        uses: ./.github/workflows/build

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-${{ github.sha }}

      - name: Show
        run: |
          pwd
          ls -alh
